### ISSUE TITLE
Add variable exports for depends_on workaround

### ISSUE THREAD

**Issue by kpitzen** [salte-io/terraform-aws-serverless#3]
Currently, Terraform doesn't handle modules as a dependency for other resources very well.  The present workaround is to import a variable from the dependency to the dependent resource to force terraform to handle things in the correct order.  Without an exported variable, there's no way to tie into this functionality.

**Comment by cecilia-sanare** [comment]
I know @davewoodward has run into this issue before on other projects. 

Feel free submit a PR if you have time or link a few references and I'll take a look at it later!

**Comment by kpitzen** [comment]
hcl format seems to have added some whitespace diffs.  If you'd rather keep your formatting, I can remove them, but it's sort of aesthetically pleasing :)

**Comment by cecilia-sanare** [comment]
I’m fine with your formatting. 
I’ll try to look at it in the next hour.

**Comment by cecilia-sanare** [comment]
This has been published in version [1.1.0](https://github.com/salte-io/terraform-aws-serverless/releases/tag/1.1.0)!
